name: appointment_booking_challenge
description: "Appointment booking challenge - Enpal."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  auto_route: ^9.2.2

  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1

  shared_preferences: ^2.3.4

  injectable: ^2.5.0

  flutter_styled_toast: ^2.2.1

  dio: ^5.7.0

  get_it: ^8.0.3

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner:
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable:

flutter:
  uses-material-design: true
