name: backend_service
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^3.4.8

  json_annotation: ^4.9.0
  intl: ^0.20.1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0

  json_serializable:
  build_runner:
  mockito: ^5.4.4
